branches:
  except:
    - gh-pages

language: python

python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"

env:
    - PIP_USE_MIRRORS=true

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script: "py.test"

matrix:
  allow_failures:
    - python: "3.1"
    - python: "3.2"
    - python: "3.3"